// Generated by CoffeeScript 1.12.3
(function() {
  $(function() {
    return app.initialize();
  });

  window.app = {
    life: {
      my: 3,
      enemy: 3
    },
    initialize: function() {
      return this.setBind();
    },
    setBind: function() {
      $('#gamestart').on('click', (function(_this) {
        return function() {
          _this.showHand();
          return _this.timer();
        };
      })(this));
      $('#gamerestart').on('click', (function(_this) {
        return function() {
          return _this.reset('clear', 'over');
        };
      })(this));
      $('#gu').on('click', (function(_this) {
        return function() {
          return _this.clickHand(1);
        };
      })(this));
      $('#tyoki').on('click', (function(_this) {
        return function() {
          return _this.clickHand(2);
        };
      })(this));
      return $('#pa').on('click', (function(_this) {
        return function() {
          return _this.clickHand(3);
        };
      })(this));
    },
    showHand: function() {
      $('#gamestart').fadeOut('fast');
      return $('#open').fadeIn('normal');
    },
    timer: function() {
      var m;
      m = $('#m');
      return setInterval((function(_this) {
        return function() {
          var val;
          m.html5jpMeterPolyfill();
          val = parseFloat(m.attr('value'), 10);
          val -= 0.05;
          m.attr('value', val);
          console.log(val);
          if (val <= 0) {
            _this.life.my--;
            _this.decrease_life(_this.life.my, 'my');
            _this.damaged('me');
            return m.attr('value', 5);
          }
        };
      })(this), 50);
    },
    clickHand: function(mynumber) {
      var enemynumber, m;
      enemynumber = _.random(1, 3);
      this.display_img(enemynumber, 'you');
      this.display_img(mynumber, 'me');
      this.judgement(mynumber, enemynumber);
      m = $('#m');
      return m.attr('value', 5);
    },
    judgement: function(mynumber, enemynumber) {
      if (mynumber === enemynumber) {
        return $('#judge').text('引き分けです!');
      } else if (mynumber - enemynumber === -2 || mynumber - enemynumber === 1) {
        this.life.my--;
        this.decrease_life(this.life.my, 'my');
        $('#judge').text('あなたの負けです!');
        return this.damaged('me');
      } else {
        this.life.enemy--;
        this.decrease_life(this.life.enemy, 'enemy');
        $('#judge').text('あなたの勝ちです！');
        return this.damaged('you');
      }
    },
    damaged: function(who) {
      return $("." + who).fadeOut('fast', function() {
        return $("." + who).fadeIn('fast');
      });
    },
    display_img: function(image_number, who) {
      switch (image_number) {
        case 1:
          return $("." + who).attr('src', 'img/グー.jpg');
        case 2:
          return $("." + who).attr('src', 'img/チョキ.jpg');
        case 3:
          return $("." + who).attr('src', 'img/パー.jpg');
      }
    },
    check: function(mynumber, enemynumber) {
      console.log(mynumber);
      return console.log(enemynumber);
    },
    decrease_life: function(lifepoint, who) {
      $("." + who + "life_" + lifepoint).hide(1000);
      if (lifepoint === 0 && who === 'enemy') {
        return setTimeout((function(_this) {
          return function() {
            return _this.result('clear');
          };
        })(this), 1350);
      } else if (lifepoint === 0 && who === 'my') {
        return setTimeout((function(_this) {
          return function() {
            return _this.result('over');
          };
        })(this), 1350);
      }
    },
    result: function(which) {
      $('#open').fadeOut('fast');
      $("#game" + which).fadeIn(500);
      return $('#gamerestart').fadeIn('500');
    },
    reset: function(win, lose) {
      var i, j, m;
      $('#gamerestart').fadeOut('fast');
      $("#game" + win).fadeOut('fast');
      $("#game" + lose).fadeOut('fast');
      $('.me').attr('src', 'img/はてな.jpg');
      $('.you').attr('src', 'img/はてな.jpg');
      $('#judge').text('勝敗は？');
      for (i = j = 0; j <= 2; i = ++j) {
        $(".mylife_" + i).fadeIn('normal');
        $(".enemylife_" + i).fadeIn('normal');
      }
      this.life.my = 3;
      this.life.enemy = 3;
      m = $('#m');
      m.attr('value', 5);
      return this.showHand();
    }
  };

}).call(this);
